# --- !Ups
CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  notifications VARCHAR(255),
  is_prime BOOLEAN DEFAULT FALSE,
  role VARCHAR(50) DEFAULT 'customer' 
  
);


CREATE TABLE IF NOT EXISTS items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  stock BIGINT NOT NULL,
  minStock BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS refs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ref VARCHAR(955) NOT NULL,
  userId BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item BIGINT NOT NULL,
  qty BIGINT NOT NULL,
  CONSTRAINT fk_order_item FOREIGN KEY (item) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS restock (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  itemId BIGINT NOT NULL,
  customerId BIGINT NOT NULL,
  CONSTRAINT fk_restock_item FOREIGN KEY (itemId) REFERENCES items(id),
  CONSTRAINT fk_restock_customer FOREIGN KEY (customerId) REFERENCES users(id)
);

ALTER TABLE refs
MODIFY COLUMN ref TEXT NOT NULL;


# --- !Downs
DROP TABLE IF EXISTS restock;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
