# --- !Ups

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS restock;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS refes;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;



CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255),
  notifications VARCHAR(255),
  is_prime BOOLEAN DEFAULT FALSE,
  address VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'customer'
);

CREATE TABLE items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  stock BIGINT NOT NULL,
  minStock BIGINT NOT NULL
);

CREATE TABLE refes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  ref VARCHAR(955) NOT NULL
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item BIGINT NOT NULL,
  qty BIGINT NOT NULL,
  CONSTRAINT fk_order_item FOREIGN KEY (item) REFERENCES items(id)
);

CREATE TABLE restock (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  itemId BIGINT NOT NULL,
  customerId BIGINT NOT NULL,
  CONSTRAINT fk_restock_item FOREIGN KEY (itemId) REFERENCES items(id),
  CONSTRAINT fk_restock_customer FOREIGN KEY (customerId) REFERENCES users(id)
);
