version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 000000
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p'000000'"]
      interval: 10s
      timeout: 10s
      retries: 5

  notification-service:
    image: Grpc-noti/notification-service:1.0-SNAPSHOT
    build:
      context: . 
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9001:9001"
      - "50052:50052"
    environment:
      DB_HOST: mysql
      DB_NAME: testdb
      DB_USER: root
      DB_PASSWORD: 000000
volumes:
  mysql-data:

