name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-all:
    name: Build All Projects
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Step 1: Build and publish grpc-app locally
      - name: Build grpc-app
        working-directory: ./grpc/hello-world
        run: sbt clean compile publishLocal

      # Step 2: Build and test stock-alert
      - name: Build & Test Stock Alert
        working-directory: ./stock-alert
        run: sbt clean compile test

      # Step 3: Build and test notification service
      - name: Build & Test Notification Service
        working-directory: ./noti
        run: sbt clean compile test
