jobs:
  build-grpc:
    name: Build & Publish gRPC
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grpc
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Run sbt publishLocal
        run: sbt clean compile publishLocal

  build-stock-alert:
    name: Build & Test Stock Alert
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stock-alert
    needs: build-grpc  # ensures grpc is published locally first
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Run sbt tests
        run: sbt clean compile test

  build-noti:
    name: Build & Test Notification Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./noti
    needs: build-grpc  # ensures grpc is published locally first
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Run sbt tests
        run: sbt clean compile test
