name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-stock-alert:
    name: Build & Test Stock Alert
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stock-alert
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        with:
          java-version: '21'

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run sbt tests
        run: sbt clean compile test

  build-notification:
    name: Build & Test Notification Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./noti
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        with:
          java-version: '21'

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run sbt tests
        run: sbt clean compile test
