name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-all:
    name: Build & Test All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        with:
          java-version: '21'

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # 1️⃣ Build GRPC first
      - name: Build & publish grpc locally
        working-directory: ./grpc/hello-world
        run: sbt clean compile publishLocal

      # 2️⃣ Build Stock Alert
      - name: Build & test stock-alert
        working-directory: ./stock-alert
        run: sbt clean compile test

      # 3️⃣ Build Notification Service
      - name: Build & test noti
        working-directory: ./noti
        run: sbt clean compile test
