name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-all:
    name: Build All Projects
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: stockuser
          MYSQL_PASSWORD: stockpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Step 1: Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysql -h 127.0.0.1 -u stockuser -pstockpass -e "SELECT 1" && break
            echo "Waiting 2 seconds..."
            sleep 2
          done

      # Step 2: Build and publish grpc-app locally
      - name: Build grpc-app
        working-directory: ./grpc/hello-world
        run: sbt clean compile publishLocal

      # Step 3: Build & Test Stock Alert
      - name: Build & Test Stock Alert
        working-directory: ./stock-alert
        run: sbt clean compile test

      
