name: StockAlert Multi-Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # =========================================================
  # CI for stock-alert project
  # =========================================================
  stock-alert:
    name: Build & Test - Stock Alert API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stock-alert
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('stock-alert/**/build.sbt') }}

      - name: Build & Test using sbt
        run: sbt clean compile test

  # =========================================================
  # CI for notification-service (noti)
  # =========================================================
  noti:
    name: Build & Test - Notification Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: noti
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache sbt dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('noti/**/build.sbt') }}

      - name: Build & Test using sbt
        run: sbt clean compile test
